blog/urls.py
from django.conf.urls import url
from django.urls import include,path
from . import views
#for Second API

app_name = 'Post'
urlpatterns = [
    path('',views.all_post,name='all_post'),
    path('<int:id>' , views.post ,name='post'),
    path('create/',views.create_post,name='create_post'),
    path('<int:id>/edit' , views.edit_post ,name='edit_post'),


]

job/urls.py
from django.urls import path

from . import views
from . import api

app_name = 'job'
urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.addjob,name='add_job'),
    path('<str:slug>',views.job_detail,name='job_det'),
   
   #API
    path('api/jobs',api.job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),


    # class based views
    path('api/v2/jobs',api.JobListApi.as_view(),name= 'job_list_api'),
    path('api/v2/jobs/<int:id>',api.JobDetailApi.as_view(),name= 'job_detail_api')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('job.urls',namespace='jobs')),
    path('contacts/',include('contact.urls',namespace='contacts')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('api-auth', include('rest_framework.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.




class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=50)
    content=RichTextField()
    img=models.ImageField(upload_to='post_img/',default="post_img/default.jpg")
    created=models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    class Meta:
        db_table = 'Posts'
        managed = True
        verbose_name = 'Posts'
        verbose_name_plural = 'Postss'
    

blog/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title','content','img']

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post
from .forms import PostForm

def all_post(request):
    all_posts= Post.objects.filter(active = True)
    context = {
        'all_posts':all_posts,
    }
    return render(request,'allposts.html',context)



def post(request , id):
    #post=Post.objects.get(id=id)
    post = get_object_or_404(Post,id=id)
    context= {
        'post' : post
    }
    return render(request , "post.html",context)

def create_post(request):
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            newform=form.save(commit=False)
            newform.user=request.user
            newform.save()
            return redirect('/')

    else:
        form = PostForm()
    
    context = {
        'form': form ,
    }

    return render(request,'create.html',context)

def edit_post(request,id):
    post = get_object_or_404(Post ,id=id )
    if request.method=='POST':
        form=PostForm(request.POST,instance=post)
        if form.is_valid():
            newform=form.save(commit=False)
            newform.user=request.user
            newform.save()
            return redirect('/')

    else:
        form = PostForm(instance=post)
    
    context = {
        'form': form ,
    }

    return render(request,'edit.html',context)

blog/templates/allposts.html
{% extends "base.html" %}
<!-- <h1>Welcome to my Blog</h1>
<a href="{% url 'blog:create_post'  %}">Add New Post</a>

{% for post in all_posts %}
    <h3> <a href=" {% url 'blog:post' post.id %}">{{ post.title}}</a> </h3>
{% endfor %} -->

{% block body %}
          <!-- bradcam_area  -->
          <div class="bradcam_area bradcam_bg_1">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="bradcam_text">
                            <h3>{{all_posts|length}}+ Posts Available</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ bradcam_area  -->
     
     <div class="mt-50">
      
      {% if user.is_superuser %}
      <div>
        <button type="button" class="btn btn-dark mr-4 float-right" ><a href="{% url 'blog:create_post' %}" style="color: white; text-decoration: none;" >Add Post</a></button>
      </div>
      {% else %}
      <div></div>
      {% endif %}
        
      <div class="container">
        <div class="row mt-4">
          {% for post in all_posts %}
          <div class="col-md-4">

            <div class="card">
                {% if post.img %}
                <img src="{{ post.img.url }}" class="card-img-top" alt="...">
                {% endif %}

                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <p class="card-text" >{{ post.content|safe|truncatewords:10}}</p>
                  <a href="{% url 'blog:post' post.id %}" class="btn btn-primary">Know more</a>
                </div>
              </div>

           </div> 
           
          {% endfor %}
         
        </div>
      </div>
     </div>

      {% endblock body %}

blog/templates/create.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
 <!-- bradcam_area  -->
 <div class="bradcam_area bradcam_bg_1">
    <div class="container">
     
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div style="width: 80%; margin: 5%;">
    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.media}}    
        {% bootstrap_form form%}
    
        {%buttons%}
        <button type="submit" class="btn btn-primary">save Post</button>
        {% endbuttons%}
    
    </form>
</div>

{% endblock body %}

blog/templates/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
        <!-- bradcam_area  -->
        <div class="bradcam_area bradcam_bg_1">
            <div class="container">
              
            </div>
        </div>
        <!--/ bradcam_area  -->
<div style="width: 80%; margin: 5%;">
    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.media}}    
        {% bootstrap_form form%}
    
        {%buttons%}
        <button type="submit" class="btn btn-primary">save Post</button>
        {% endbuttons%}
    
    </form>
</div>

{% endblock body %}
    

blog/templates/post.html
{% extends "base.html" %}
<!-- {{post}}<br>
{{post.content}} -->
<!-- <hr>
<a href="{% url 'blog:edit_post' post.id %}">Edit Post</a> -->

{% block body %}
        <!-- bradcam_area  -->
        <div class="bradcam_area bradcam_bg_1">
          <div class="container">
              
          </div>
      </div>
      <!--/ bradcam_area  -->
      
      {% if user.is_superuser %}
        <div class="mt-30">
          <button type="button" class="btn btn-dark mr-4 float-right" ><a href="{% url 'blog:edit_post' post.id %}" style="color: white; text-decoration: none;" >update Post</a></button>     
        </div>
      {% else %}
      <div></div>
      {% endif %}
        


<div class="container">
  <div class="row mt-4">
      <div class="card single_post">
          <img  src="{{ post.img.url }}" class="card-img-top" alt="card img cap">
          <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.content|safe}}</p>
          </div>
     </div> 

     

  </div>
</div>

{% endblock body %}