accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
   path('signup/',views.signup,name = 'signup'),
   path('profile/',views.profile,name = 'profile'),
   path('profile/edit',views.profile_edit,name = 'profile_edit'),
]

job/urls.py
from django.urls import path

from . import views
from . import api

app_name = 'job'
urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.addjob,name='add_job'),
    path('<str:slug>',views.job_detail,name='job_det'),
   
   #API
    path('api/jobs',api.job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),


    # class based views
    path('api/v2/jobs',api.JobListApi.as_view(),name= 'job_list_api'),
    path('api/v2/jobs/<int:id>',api.JobDetailApi.as_view(),name= 'job_detail_api')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('job.urls',namespace='jobs')),
    path('contacts/',include('contact.urls',namespace='contacts')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('api-auth', include('rest_framework.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey('City',related_name='user_city',on_delete=models.CASCADE,blank=True, null=True) 
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile/')
    

    def __str__(self):
        return str(self.user)
    
@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
       Profile.objects.create(user=instance)

class City(models.Model):
    name =models.CharField(max_length=30)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignUpForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.shortcuts import render,redirect
from .forms import SignUpForm,UserForm,ProfileForm
from django.contrib.auth import authenticate,login
from .models import Profile
from django.urls import reverse
# Create your views here.

def signup(request):
    
    if request.method =='POST':
        form = SignUpForm(request.POST)
        if form.is_valid:
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = SignUpForm()

    context ={
        'form':form
    }
    return render(request,'registration/signup.html',context)

def profile(request):
    profile = Profile.objects.get(user=request.user)
    user = request.user
    context = {
        'profile':profile
    }
    return render(request,'accounts/profile.html',context)

def profile_edit(request):
    profile =Profile.objects.get(user=request.user)

    if request.method =='POST':
        user_form = UserForm(request.POST,instance=request.user)
        profile_form = ProfileForm(request.POST,request.FILES,instance=profile,)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            my_profile = profile_form.save(commit=False)
            my_profile.user = request.user
            my_profile.save()
            return redirect(reverse('accounts:profile'))
    
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)
    
    context={
        "userform":user_form,
        'profileform':profile_form
    }
    return render(request,'accounts/profile_edit.html',context)  

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4  %}
{% block body %}
      <!-- bradcam_area  -->
      <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
           
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                       
                       {% if profile.image %}
                       <p>Image</p>
                       <img class="ilstration_img w-25" src="{{profile.image.url}}" alt="">
                       {% endif %}
                           
                        <div class="job_content">
                           
                            <ul>

                                <li>First Name: <span>{{profile.user.first_name}}</span></li>
                                <li>Last Name: <span>{{profile.user.last_name}}</span></li>

                                <li>User Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>

                            </ul>
                            
                        </div>
                        <div class="p-5 ">
                            <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-50">Edit Profile</a>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

{% endblock body %}
 

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4  %}
{% block body %}
      <!-- bradcam_area  -->
      <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                  
                   
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                           {% bootstrap_form userform%}
                           {% bootstrap_form profileform%}
                            {%buttons%}
                            <button class="boxed-btn3 w-100" type="submit">Save Changes</button>
                            {%endbuttons%}
                        </form>
                    </div>
                </div>
       
            </div>
        </div>
    </div>

{% endblock body %}
 